---
language: ruby
rvm:
- 2.0.0
env:
  matrix:
  - DB: postgresql
  global:
  - secure: |-
      fD2O/w2tyJljR7SSBYjbDPOeRZFg58oPoD5FxYfW74CD/j1foK4ZB+Ovc0Lr
      gEAYrOPkK+FKgHnKJgg27qse2LE3IQi5MCKkvIkGToG+705NkcQu6RoS3YfU
      HVI+tZLcu4zat7L/xZYEwE/V/JekCyhjy6QTtDiqNX/yCk0pGXA=
  - secure: |-
      YTHn5tmeWgoyGQ6RGRRmC/GfYescEac72g4Zmd/fScu7tR4DgcwvrNdFOdm/
      JUxYLTQDFJMFBNo4ziRyTpFN0poI8u3YYF+JWiGyXL9DivHeWeKKsZnVbKuz
      bxtxmkjb3hdDrWFoPKCLXdYM9WY/b2MITVvtJRkBjb0ojg9xr4Y=
  - secure: |-
      Cl9ByU+EoOgMsWbKgf0HJkjezWkKPs4WovhOYkNYT41+TxEzqHUP+RMOoIsn
      A0mhGf4k1EsLUjIltT4VFyN9bQIdleH+33OuC20/Q4dbfEnlbe3G0PMlqjdW
      FjjKtmMDSQ/dCABpLUWH+nREhI2da0Po0VcZJq6geYQlcd+Wesk=
  - secure: |-
      H0V5X3Gg83amUISOwpKCMWpZskWG20m6+Es9mqGY/7mAeHWubRW5okhEd+fK
      zvsUVWkTc5ZRUlKNUUCI4OWVDjotxTMM3Q76ljPXFLPz3xdl5+0YpXo8LvnU
      vvevciA8m880RoZGh0QFdHe5a7I4913bvXe6mAg/9jP0Ie1E9ck=
  - secure: |-
      ZcxEehI57TGds7geXoqurdFDA0Ru7uNoTIf7Fkeam+Nc0Bt3/k+hzwZfdPHv
      EEohvm4tXPOOUUptpT6HvnFg238kOWFR93RbcNXZlgQ6ie2lEfweq/HKfYTt
      QYzIFCoecxbPc5tmgZm0D6KnKCaJQShThBDYeSwSqlaIp1/PtYM=
bundler_args: --without development
before_script:
- psql -c "create database $DB_NAME;" -U $DB_USER
- RAILS_ENV=test bundle exec rake db:migrate --trace
script:
- bundle exec rspec --no-drb --format progress spec/
deploy:
  provider: heroku
  app: $HEROKU_APP_NAME
  api_key: $HEROKU_API_KEY
  # strategy: git
