---
language: ruby
rvm:
- 2.0.0
env:
  matrix:
  - DB: postgresql
  global:
  - secure: |-
      Xgd562z6Tl5cYewlSoX2jOdv+3jxdN2ihJ1kBVBT3fbZ2wmVyibW/dZa77e7
      f7GPXkNMjZRRoVOaNU7vr21HBNPB+ofNaZ7dJkqorXAFHS8YKKTwDqsYpMSN
      QpE6tf3GxswukrYgnzrsO1sF/Vh4CtSJBiyIt0PdM9bmBic2Lz0=
  - secure: |-
      UE8cZHDN1ckKC82vNPzd/Jwx4T185biRX/0aXgjyePLyKqoWZrGxSOKiqsdO
      RBOUNjNEYx0StJy0vdeFxmUe0jKLe4owNM+OoDMKfcbnyuH5aOb4GALyPC4P
      yPRtka30CoS4HQmiaRNq1a644U5iPHnCxUmPpbc1LtYRg4hxIF4=
  - secure: |-
      fD2O/w2tyJljR7SSBYjbDPOeRZFg58oPoD5FxYfW74CD/j1foK4ZB+Ovc0Lr
      gEAYrOPkK+FKgHnKJgg27qse2LE3IQi5MCKkvIkGToG+705NkcQu6RoS3YfU
      HVI+tZLcu4zat7L/xZYEwE/V/JekCyhjy6QTtDiqNX/yCk0pGXA=
  - secure: |-
      YTHn5tmeWgoyGQ6RGRRmC/GfYescEac72g4Zmd/fScu7tR4DgcwvrNdFOdm/
      JUxYLTQDFJMFBNo4ziRyTpFN0poI8u3YYF+JWiGyXL9DivHeWeKKsZnVbKuz
      bxtxmkjb3hdDrWFoPKCLXdYM9WY/b2MITVvtJRkBjb0ojg9xr4Y=
  - secure: |-
      Cl9ByU+EoOgMsWbKgf0HJkjezWkKPs4WovhOYkNYT41+TxEzqHUP+RMOoIsn
      A0mhGf4k1EsLUjIltT4VFyN9bQIdleH+33OuC20/Q4dbfEnlbe3G0PMlqjdW
      FjjKtmMDSQ/dCABpLUWH+nREhI2da0Po0VcZJq6geYQlcd+Wesk=
bundler_args: --without development
before_script:
- psql -c "create database $DB_NAME;" -U $DB_USER
- RAILS_ENV=test bundle exec rake db:migrate --trace
script:
- bundle exec rspec --no-drb --format progress spec/
after_success:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku $HEROKU_GIT_URL
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- yes | git push heroku master
