language: ruby
rvm:
- 2.2.2
env:
  matrix:
  - DB: postgresql
  global:
  - secure: |-
      HtPRbdmF7kIEb7vyPHjdxSiZoiyp5Q3ZJti6qzZsCCZ6KOXKMpign806wcSl
      5X9YcpnaG918/KA5UClgAMo+n5/RXjrs0VxnaQhLi1OXuGncntsHU+8MbVsy
      Fmnj8w4bu4kWOIp4xxxFCodlL68XmSNsfX0Th9dZnG8e7Xb/S50=
  - secure: |-
      FaLVkMuq9uLYp8sAR4IZwM51fF59dHCCVPvRSkmyuHvZHoUItiscAWSZcPMD
      JbsILcaGBnMKHzfpCecQnrwObdDlmSzORsWnBqPso4u+AKooO7y3tKwu7Yy4
      N3SpvzyCO6hUYtqtEK+5d2VQYDOh1oBVbyjk44rrep5KaqKDb3Q=
  - secure: |-
      BNa/3KSDeCb3D4L9yzkJ2DtSfsuI+zkUPHHSJ60yyp6QEuQ+YtG5M+jVJIBW
      W8qBAb6o3K8GIwTlF8v8Rgs/TG1oSMEEXIFjTUPOn+cEinuRIYsi99q1tKmf
      ZjoXE3a1rx6rKVpRjozEDjlURG3o362ntRA6yzM4fOGOtDR9IXY=
  - secure: |-
      capKgfKHBgFlGfREst/3CRR5I5gth49xZbXGUPmQKCMc5WieKB87hroMowaL
      lLpvcgh8moPPgCpiWZ62cbpYC93si9A+h0asOlLmfDi0TDq9J87ydmposVk3
      cktJuzB+ofH7KpUKGQ+NZRsc8fiUNsAA083uGPep0mZg8WYhpHc=
  - secure: |-
      YgUM9WVqfUGCSa02MgRac0ZAvv2ZS9+EFdqxvsI8cV/aZWgO2zTtcDSM0n3i
      oXb0OWxPPGjjQf2GlNC9sSDiJZD1jXT8epN0vFmfZvSuCtiVoH0QUYJn43y7
      tGXhlYaMTpYTnEsPjgg2r3WkZ4VTSsML3EneUxvIfnwsvNgQ7t4=
  - secure: |-
      WxUi2KjjK2Yof+3yEUdg/itVGdGxsmW7lZ/DE77P81RfAFTJycvORifE3Lk+
      yfKOIMxHuwHe+l37jkn/UxxLRsvhFgkFpOXv7PPbKZO7bsAmQRdLcY/F3huC
      YZCayo701Vx9N+DS/JBrru0C2hz19HW2njE7rWXL7qr3XcP0rlA=
  - secure: |-
      gIu7Ek0BobZSg5nKq1z4z4G/CTKBFGtD222UhiMYi0nd0JTdESDUsjLwW3tu
      piNXu+CWWoAFV2E/C4E49aTezsKH7hHO+UUuozyyp2TAAQwP7OjiJFt2XdGh
      GbK+w2E/iALf0ftW1d89qSuBgunrF5VSKkeO2wdBQEdWmDUgjHc=
  - secure: |-
      U/L5Pb5+ti4EOJlbXUO62pnjB9wHTtot0f295mILIHoqJv+/QL6eT3DZJpFk
      0pi/7jquJd9MbU5Ik2cPf3PrpvqcRKqLmeZ1heS8C0TW1lEtbcovLtCPq+BB
      GNI7ctTWaTVRJE/usE4c6oyXuly8K5T1dvi4qbXVPlupWHAM4sM=
  - secure: |-
      On6nU1dLy9Z/cW9DCjz5H29xl1O3wMllsQWo0ux34jpJr6O7WMKZNlp+A6+C
      yd+btt7r5BwofZVwOUr8pGTk2ec00krfaNX9sOgkhSohB5XDmBn9JBQffMO9
      qzIXVBq3J+X5dgXCZqkeZgcv2R+ocG6eQPBkhKXYHEjuuACtC28=
  - secure: |-
      QY+iRat9cjaIMSai1ihoV3/3lEGf6Mf0Q2YGRS4cALYnbgessD9FjPuuo7aR
      qZRAJkX/N1BbHMCeMaFpJHLn80fZMvdKZH8xfpFzGeCgN60Rib8D1xvYXc6s
      /RuydqzeqjLauIr1+R9udEfIWHPcpGuuo+qOpuJoEuvyNzfhU3s=
bundler_args: --without development
before_script:
- psql -c "create database $DB_NAME_TEST;" -U $DB_USER_TEST
- RAILS_ENV=test bundle exec rake db:migrate
script:
- bundle exec rspec --no-drb --format progress spec/
deploy:
  provider: heroku
  app: $HEROKU_APP_NAME
  api_key: $HEROKU_API_KEY
  run: rake db:migrate
  on:
    rvm: <%= ruby File.read('.ruby-version').chomp %>
