---
language: ruby
rvm:
- 2.0.0
env:
  matrix:
  - DB: postgresql
  global:
  - secure: |-
      fD2O/w2tyJljR7SSBYjbDPOeRZFg58oPoD5FxYfW74CD/j1foK4ZB+Ovc0Lr
      gEAYrOPkK+FKgHnKJgg27qse2LE3IQi5MCKkvIkGToG+705NkcQu6RoS3YfU
      HVI+tZLcu4zat7L/xZYEwE/V/JekCyhjy6QTtDiqNX/yCk0pGXA=
  - secure: |-
      YTHn5tmeWgoyGQ6RGRRmC/GfYescEac72g4Zmd/fScu7tR4DgcwvrNdFOdm/
      JUxYLTQDFJMFBNo4ziRyTpFN0poI8u3YYF+JWiGyXL9DivHeWeKKsZnVbKuz
      bxtxmkjb3hdDrWFoPKCLXdYM9WY/b2MITVvtJRkBjb0ojg9xr4Y=
  - secure: |-
      Cl9ByU+EoOgMsWbKgf0HJkjezWkKPs4WovhOYkNYT41+TxEzqHUP+RMOoIsn
      A0mhGf4k1EsLUjIltT4VFyN9bQIdleH+33OuC20/Q4dbfEnlbe3G0PMlqjdW
      FjjKtmMDSQ/dCABpLUWH+nREhI2da0Po0VcZJq6geYQlcd+Wesk=
  - secure: |-
      dalHvQo1esdU2DN2XXv0kscXliqt42kTPBF0XiRBlzngGppW4e4320Zu64nL
      OQJvxKXjiKMPjWHwMyTwkdmIgQuicNSTGKH7+CKlK+R+uEoaXhCLVMUYrdO6
      GF7dK0PmxtkYsWX2I/3YkiCXwF1P6mQBQbdnQKivE4Qt7KWnYg0=
  - secure: |-
      IrkK84+ZZy6ZS/9tfwn8K8wNKfCnmCSpcY2RQnOWpnZwSxlrqNDE/X61+owR
      rasBvgAdBYhg/7XBa08YTEeKOL/ktZn27+tmLQ9rr7LhZH+/NuHxIUHIDisn
      zVOGi9wfgYqnXeZ/KVB71lsv072KruBTVjv+liyZ1gI+BVP0fKY=
bundler_args: --without development
before_script:
- psql -c "create database $DB_NAME;" -U $DB_USER
- RAILS_ENV=test bundle exec rake db:migrate --trace
script:
- bundle exec rspec --no-drb --format progress spec/
deploy:
  provider: heroku
  app: $HEROKU_APP_NAME
  api_key: $HEROKU_API_KEY
