# App keys

# rake secret generates a key of 128 characters.
# Use 114 of those characters if you want to use the secret_key_base
# as a secure config variable called SK in your Travis build and deploy
SK: # your secret_key_base from secret_token.rb here

development:
  DB_NAME: # your dev db name here
  DB_USER: # your dev db username here
  DB_PASSWORD: # your dev db password here

test:
  DB_NAME: # your test db name here
  DB_USER: # your test db username here
  DB_PASSWORD: # your test db password here

production:
  DB_NAME: # your production db name here
  DB_USER: # your production db username here
  DB_PASSWORD: # your production db password here

HEROKU_API_KEY: # your Heroku API key here
HEROKU_APP_NAME: # your Heroku app name here eg sampleapp-rails4