# App keys
SECRET_KEY_BASE: # run rake secret to generate a secret token, then place here

development:
  DB_NAME: # your dev db name here
  DB_USER: # your dev db username here
  DB_PASSWORD: # your dev db password here

test:
  DB_NAME: # your test db name here
  DB_USER: # your test db username here
  DB_PASSWORD: # your test db password here

production:
  DB_NAME: # your production db name here
  DB_USER: # your production db username here
  DB_PASSWORD: # your production db password here