# sqlite: &sqlite
#   adapter: sqlite3
#   database: db/<%= Rails.env %>.sqlite3

# mysql: &mysql
#   adapter: mysql2
#   username: root
#   password:
#   database: <%= Rails.root.basename.to_s %>_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

defaults: &defaults
  pool: 5
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults