# sqlite: &sqlite
#   adapter: sqlite3
#   database: db/<%= Rails.env %>.sqlite3

# mysql: &mysql
#   adapter: mysql2
#   username: root
#   password:
#   database: <%= Rails.root.basename.to_s %>_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  encoding: unicode

defaults: &defaults
  pool: 5
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults
  database: <%= ENV['DB_NAME_DEV'] %>
  username: <%= ENV['DB_USER_DEV'] %>
  password: <%= ENV['DB_PASSWORD_DEV'] %>

test:
  <<: *defaults
  database: <%= ENV['DB_NAME_TEST'] %>
  username: <%= ENV['DB_USER_TEST'] %>
  password: <%= ENV['DB_PASSWORD_TEST'] %>

production:
  <<: *defaults
  database: <%= ENV['DB_NAME_PROD'] %>
  username: <%= ENV['DB_USER_PROD'] %>
  password: <%= ENV['DB_PASSWORD_PROD'] %>